export const  REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const  REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";


export const  LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const  LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const  REGISTER_SHOP_ERROR = "REGISTER_SHOP_ERROR";
export const  REGISTER_SHOP_SUCCESS = "REGISTER_SHOP_SUCCESS";

export const  REGISTER_MONEY_ERROR = "REGISTER_MONEY_ERROR";
export const  REGISTER_MONEY_SUCCESS = "REGISTER_MONEY_SUCCESS";

